---

# ansible-playbook -K -D -i inventory/hosts.yml playbook.yml --ask-vault-pass

- name: Zoneminder
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    zoneminder: {}

  roles:
    - ansibleguy.sw_zoneminder
